import { Users, TrendingUp, Award } from "lucide-react";
import { Badge } from "@/components/ui/badge";

const tiers = [
  {
    name: "Standard Partner",
    icon: Users,
    badge: "Instant Access",
    badgeVariant: "default" as const,
    directCommission: "$2.25/mo",
    networkBonus: null,
    description: "Earn recurring commissions on every active subscription you refer. Start earning immediately.",
    highlight: false,
  },
  {
    name: "Scout Partner",
    icon: TrendingUp,
    badge: "Unlock at 10 Referrals",
    badgeVariant: "secondary" as const,
    directCommission: "$2.25/mo",
    networkBonus: "$0.30/mo",
    description: "Unlock the Leadership Bonus. Earn a $0.30 network bonus on every validated sale generated by your team.",
    highlight: false,
  },
  {
    name: "Elite Partner",
    icon: Award,
    badge: "Unlock at 100 Referrals",
    badgeVariant: "secondary" as const,
    directCommission: "$2.25/mo",
    networkBonus: "$0.75 Guaranteed",
    networkBonusExtra: "Up to $1.05/mo",
    description: "Maximize your revenue. Earn a guaranteed $0.75 network bonus on every team sale, with the potential to earn up to $1.05 by capturing unclaimed bonuses.",
    highlight: true,
  },
];

const PartnerSection = () => {
  return (
    <section id="partner" className="section-padding bg-muted">
      <div className="container-narrow">
        {/* Header */}
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold text-foreground mb-4">
            Grow with NexusFlow
          </h2>
          <p className="text-lg text-muted-foreground max-w-xl mx-auto">
            Earn commissions by referring other professionals to the platform.
          </p>
        </div>

        {/* Tier Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {tiers.map((tier) => (
            <div
              key={tier.name}
              className={`relative card-elevated p-6 transition-all duration-300 hover:shadow-lg ${
                tier.highlight
                  ? "ring-2 ring-amber-400 bg-gradient-to-b from-amber-50/50 to-card dark:from-amber-900/10"
                  : ""
              }`}
            >
              {/* Badge */}
              <div className="mb-4">
                <Badge
                  variant={tier.badgeVariant}
                  className={tier.highlight ? "bg-amber-500 text-white hover:bg-amber-500" : ""}
                >
                  {tier.badge}
                </Badge>
              </div>

              {/* Header */}
              <div className="flex items-center gap-3 mb-6">
                <div
                  className={`w-12 h-12 rounded-xl flex items-center justify-center ${
                    tier.highlight
                      ? "bg-amber-100 dark:bg-amber-900/30"
                      : "bg-primary/10"
                  }`}
                >
                  <tier.icon
                    className={tier.highlight ? "text-amber-600" : "text-primary"}
                    size={24}
                  />
                </div>
                <h3 className="text-lg font-bold text-foreground">{tier.name}</h3>
              </div>

              {/* Earnings */}
              <div className="space-y-4 mb-6">
                {/* Direct Commission */}
                <div className="p-4 rounded-xl bg-secondary/50">
                  <p className="text-xs text-muted-foreground mb-1">Direct Commission</p>
                  <p className="text-2xl font-bold text-foreground">{tier.directCommission}</p>
                  <p className="text-xs text-muted-foreground">Per Personal Sale</p>
                </div>

                {/* Network Bonus */}
                <div
                  className={`p-4 rounded-xl ${
                    tier.networkBonus
                      ? tier.highlight
                        ? "bg-amber-100/50 border border-amber-200 dark:bg-amber-900/20 dark:border-amber-800"
                        : "bg-accent/10 border border-accent/20"
                      : "bg-secondary/30 border border-dashed border-border"
                  }`}
                >
                  <p className="text-xs text-muted-foreground mb-1">Network Bonus</p>
                  {tier.networkBonus ? (
                    <>
                      <p
                        className={`text-2xl font-bold ${
                          tier.highlight ? "text-amber-600" : "text-accent"
                        }`}
                      >
                        {tier.networkBonus}
                      </p>
                      {tier.networkBonusExtra && (
                        <p className="text-xs text-muted-foreground">{tier.networkBonusExtra}</p>
                      )}
                      <p className="text-xs text-muted-foreground">Per Network Sale</p>
                    </>
                  ) : (
                    <p className="text-sm text-muted-foreground">None</p>
                  )}
                </div>
              </div>

              {/* Description */}
              <p className="text-sm text-muted-foreground">{tier.description}</p>
            </div>
          ))}
        </div>

        {/* Note */}
        <p className="text-center text-sm text-muted-foreground mt-10 max-w-lg mx-auto">
          Commission is calculated based on the $15/month subscription of each active referral.
        </p>
      </div>
    </section>
  );
};

export default PartnerSection;